application.data-dir: /Users/CODE.ID/rest-service
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/inventory?serverTimezone = UTC
        url: jdbc:mysql://localhost:3306/inventory?serverTimezone = UTC
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create
            generate-ddl: true
            show-sql: true
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL8Dialect
    main.lazy-initialization: true
    messages:
        basename: i18n/messages
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB
    

                